### ISSUE TITLE
Unexpected HTTP status code: 401

### ISSUE THREAD

**Issue by b35li** [libgit2/git2go#189]
Hi All,
I moved this issue from libgit2 [#3021](https://github.com/libgit2/libgit2/issues/3021). Here is the place I got the answer from ethomson. Thank him.

I ran into an error which shows as following:
```
Starting....
panic: Unexpected HTTP status code: 401

goroutine 1 [running]:
main.clone()
	/var/www/dev/test/gitcli.go:33 +0x14f
main.main()
	/var/www/dev/test/gitcli.go:78 +0xdf

goroutine 17 [syscall, locked to thread
```

Does anybody know how I fix the problem? Thanks very much, it blocks me two days.
here is snippet of code: 
```
   import (
       "fmt"
   
       "gopkg.in/libgit2/git2go.v22"
   )
   
   func credentialsCallback(url string, username string, allowedTypes git.CredType) (git.ErrorCode, *git.Cred) {
      // Tried my OS X username, Github username and 'git' here
      // I also tried git.NewCredSshKeyFromAgent below
      ret, cred := git.NewCredSshKey("git", "~/.ssh/id_rsa.pub", "~/.ssh/id_rsa", "")
      fmt.Println(cred.Type())
      return git.ErrorCode(ret), &cred
  }
  
  // Made this one just return 0 during troubleshooting...
  func certificateCheckCallback(cert *git.Certificate, valid bool, hostname string) git.ErrorCode {
      return 0
  }
  
  func clone() {
      cb := &git.RemoteCallbacks{
          CredentialsCallback: credentialsCallback,
          CertificateCheckCallback: certificateCheckCallback,
      }
      co := &git.CloneOptions{
          RemoteCallbacks: cb,
      }
      repo, err := git.Clone("http://{username}@{internalproject}", "proj", co)
      if err != nil {
          panic(err)
      }
      fmt.Println(repo.Config())
  }


```

**Comment by b35li** [comment]
it seems not reproducible from last night. So it miiiight be the network issue in our company. just close it temporarily.
