### ISSUE TITLE
Cannot get revwalk walking

### ISSUE THREAD

**Issue by jgautheron** [libgit2/git2go#240]
Here's the code (branch `next`):
```go
rv, err := rp.Walk()
rv.Sorting(git.SortTime)
rv.PushHead()

var gi *git.Oid
for {
    err := rv.Next(gi)
    if err != nil {
        break
    }

    log.Info(gi.String())
}
```

The error:
```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x10 pc=0x4055287]

runtime stack:
runtime.gothrow(0x43cee10, 0x2a)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/sigpanic_unix.go:14 +0x5e

goroutine 1 [syscall, locked to thread]:
runtime.cgocall_errno(0x400b890, 0xc20808cb40, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/cgocall.go:130 +0xf5 fp=0xc20808cb20 sp=0xc20808caf8
github.com/jgautheron/git2go._Cfunc_git_revwalk_next(0x0, 0x4c01d70, 0x0)
	.../src/github.com/jgautheron/git2go/:2097 +0x43 fp=0xc20808cb40 sp=0xc20808cb20
github.com/jgautheron/git2go.(*RevWalk).Next(0xc208028b70, 0x0, 0x0, 0x0)
	.../src/github.com/jgautheron/git2go/walk.go:157 +0x74 fp=0xc20808cb60 sp=0xc20808cb40
main.initGenerate(0xc2080881e0)
	.../src/github.com/jgautheron/foo/main.go:181 +0x3cb fp=0xc20808ccd0 sp=0xc20808c
```
What am I missing?
Thanks!

**Comment by carlosmn** [comment]
You're passing a nil pointer to `Revwalk.Next()` so you're telling it to write the next id into address `0x0` which can never work. You need to have your own `Oid` and tell `Revwalk.Next()` its address.

**Comment by jgautheron** [comment]
Right, thanks! :+1:
