### ISSUE TITLE
On repos > 1MB -fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by sithembiso** [libgit2/git2go#310]
I have a problem that snuck up on me two days ago. I'm trying to clone a repo using `https` and strangely, this works for small repos (`<1MB` for example). But when I try it on bigger repos, I get the following panic:
```
runtime stack:
runtime.throw(0x932340, 0x2a)
	/home/sithembiso/.gvm/gos/go1.5.1/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
	/home/sithembiso/.gvm/gos/go1.5.1/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x456f92, 0xc820097d78, 0x0)
	/home/sithembiso/.gvm/gos/go1.5.1/src/runtime/cgocall.go:120 +0x11b fp=0xc820097d48 sp=0xc820097d18
github.com/libgit2/git2go._Cfunc_git_clone(0xc82003a028, 0x26fb370, 0x26fb3b0, 0x26fb550, 0xc800000000)
	??:0 +0x39 fp=0xc820097d78 sp=0xc820097d48
github.com/libgit2/git2go.Clone(0x931480, 0x2e, 0x8f0c90, 0x9, 0xc820097e78, 0x0, 0x0, 0x0)
	/home/sithembiso/Workspaces/Go/src/github.com/libgit2/git2go/clone.go:43 +0x253 fp=0xc820097de8 sp=0xc820097d78
main.main()
	/home/sithembiso/tmp/git2go-test/clone.go:35 +0x1dd fp=0xc820097f40 sp=0xc820097de8
runtime.main()
	/home/sithembiso/.gvm/gos/go1.5.1/src/runtime/proc.go:111 +0x2b0 fp=0xc820097f90 sp=0xc820097f40
runtime.goexit()
	/home/sithembiso/.gvm/gos/go1.5.1/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820097f98 sp=0xc820097f90

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/sithembiso/.gvm/gos/go1.5.1/src/runtime/asm_amd64.s:1696 +0x1
exit status 2
```
Here is the source code I am using to test this:
```go
package main

import (
	git "github.com/libgit2/git2go"
)

func credentialsCallback(url string, username string, allowedTypes git.CredType) (git.ErrorCode, *git.Cred) {
	ret, cred := git.NewCredSshKeyFromAgent(username)
	return git.ErrorCode(ret), &cred
}

func certificateCheckCallback(cert *git.Certificate, valid bool, hostname string) git.ErrorCode {
	return 0
}

func main() {
	p := "test-repo"
	url := "https://github.com/sithembiso/git2go-build"
	cbs := git.RemoteCallbacks{
		CredentialsCallback: credentialsCallback,
		CertificateCheckCallback: certificateCheckCallback,
	}
	
	fetchOpts := &git.FetchOptions{
		Headers: []string{},
		Prune: git.FetchPruneOn,
		RemoteCallbacks: cbs,
	}

	cloneOpts := &git.CloneOptions{
		Bare: false,
		FetchOptions: fetchOpts,
	}

	if _, err := git.Clone(url, p, cloneOpts); err != nil {
		panic(err)
	}
}
```
This script works if I change `https` (on the protocol) to `git`, but this is not an option for out production setup because of how authentication is implemented.

If it's any relevant, I am using the `next` branch with Git2go compiled statically.

Go version:
```
go version go1.5.1 linux/amd64
```

**Comment by sithembiso** [comment]
Is anyone able to run the code above without the panic? I had started thinking that the issue was in `libgit2` (the stack trace suggests), but I was able to get the following code working which has left me speechless:
```c
#include <git2.h>
#include <stdio.h>

static int do_clone(const char *url, const char *path)
{
        git_repository *repo = NULL;
        int ret = git_clone(&repo, url, path, NULL);
        git_repository_free(repo);
        return ret;
}

int main(int argc, char **argv)
{
        //git_threads_init();
        git_libgit2_init();
        const char *url, *path;

        url = "https://github.com/sithembiso/git2go-build";
        path = "test-repo";
        return do_clone(url, path);
}
```
The code above worked like a month ago. I have no idea what changed. I've even tried changing go versions (to `go version go1.6.1 linux/amd64`).

**Comment by carlosmn** [comment]
It's possible that we're not fully 1.6-pointer-passing-rules compliant in whatever version of git2go you're using and the Go runtime has moved some memory around, making libgit2 read or write into now-unallocated memory.

**Comment by sithembiso** [comment]
I've just found a solution: Actually, there was nothing wrong with `libgit2` and `git2go`. I found out, when I was compiling `git2go` (installing it rather), it was linking to the wrong `libhttp_parser` causing issues at runtime. As a result, `libgit2` was not understanding the server response. 

I will not close this as it now seems invalid.
