### ISSUE TITLE
Unable to run tests. "make test" process keeps getting sig-killed

### ISSUE THREAD

**Issue by kidonchu** [libgit2/git2go#373]
Environment
```
os: MacOS Sierra 10.12.4 
go: 1.7.1
commit: 5d0a4c7
```

After I checked out the `next` branch, I am trying to run test with `make test` command but it keeps getting sig-killed with an error code 137 (this also happens on `master` branch). What would be causing this issue? Here is what I'm doing.

```
$> go get -d github.com/libgit2/git2go
$> cd $GOPATH/src/github.com/libgit2/git2go
$> git checkout next
$> git submodule update --init
$> make test
./script/build-libgit2-static.sh
+ VENDORED_PATH=vendor/libgit2
+ cd vendor/libgit2
+ mkdir -p install/lib
+ mkdir -p build
+ cd build
+ cmake -DTHREADSAFE=ON -DBUILD_CLAR=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=../install ..
-- Found Security /System/Library/Frameworks/Security.framework
-- Found CoreFoundation /System/Library/Frameworks/CoreFoundation.framework
-- Found Iconv: -L/usr/lib -liconv
-- Performing Test IS_WSTRICT-ALIASING=2_SUPPORTED
-- Performing Test IS_WSTRICT-ALIASING=2_SUPPORTED - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/kchu/projects/go/src/github.com/libgit2/git2go/vendor/libgit2/build
+ cmake --build .
[100%] Built target git2
go run script/check-MakeGitError-thread-lock.go
go test ./...
signal: killed
FAIL    github.com/libgit2/git2go       0.003s
make: *** [test] Error 1
```

I also created a simple program that imports git2go but still getting the process killed.
```
package main
import (
	"fmt"
	git "github.com/libgit2/git2go"
)
func main() {
	fmt.Println("Hello World")
}
func anotherFunc(cert *git.Certificate) {}
```

What could be causing this issue?

**Comment by kidonchu** [comment]
For an update, I am also getting these errors when I make install for the first time,
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libgit2.a(auth_negotiate.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libgit2.a(winhttp.c.o) has no symbols
```
Maybe this is related to why git2go is getting sig-killed.

**Comment by powerman** [comment]
Not sure is this is same issue, but on my system (Linux) tests pass about 1 of 3 times, while in 2 other I get this:
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x969051cfd5b]

runtime stack:
runtime.throw(0x969052234b2, 0x2a)
	/usr/lib/go/src/runtime/panic.go:596 +0x97
runtime.sigpanic()
	/usr/lib/go/src/runtime/signal_unix.go:274 +0x2df

goroutine 55 [syscall, locked to thread]:
runtime.cgocall(0x9690515a0a0, 0xc420511e18, 0xc4201ca410)
	/usr/lib/go/src/runtime/cgocall.go:131 +0xe8 fp=0xc420511de8 sp=0xc420511da8
github.com/libgit2/git2go._Cfunc_git_remote_fetch(0x6b4284048bd0, 0xc4201ca410, 0x6b4284006110, 0x0, 0x0)
	github.com/libgit2/git2go/_test/_obj_test/_cgo_gotypes.go:5468 +0x4f fp=0xc420511e18 sp=0xc420511de8
github.com/libgit2/git2go.(*Remote).Fetch.func3(0x6b4284048bd0, 0xc4201ca410, 0x6b4284006110, 0x0, 0x96904fb890a)
	/home/powerman/gocode/src/github.com/libgit2/git2go/remote.go:708 +0x14b fp=0xc420511e60 sp=0xc420511e18
github.com/libgit2/git2go.(*Remote).Fetch(0xc42031e550, 0xc4201e5f00, 0x0, 0x0, 0xc42040e000, 0x0, 0x0, 0x0, 0x0)
	/home/powerman/gocode/src/github.com/libgit2/git2go/remote.go:708 +0x273 fp=0xc420511eb8 sp=0xc420511e60
github.com/libgit2/git2go.TestCertificateCheck(0xc42016c750)
	/home/powerman/gocode/src/github.com/libgit2/git2go/remote_test.go:52 +0x202 fp=0xc420511fa8 sp=0xc420511eb8
testing.tRunner(0xc42016c750, 0x969054f4510)
	/usr/lib/go/src/testing/testing.go:657 +0x98 fp=0xc420511fd0 sp=0xc420511fa8
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420511fd8 sp=0xc420511fd0
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:697 +0x2cc

goroutine 1 [chan receive]:
testing.tRunner.func1(0xc420080a90)
	/usr/lib/go/src/testing/testing.go:633 +0x17d
testing.tRunner(0xc420080a90, 0xc42005dde0)
	/usr/lib/go/src/testing/testing.go:659 +0xa2
testing.runTests(0xc42000cfc0, 0x969055c6340, 0x48, 0x48, 0x300000002)
	/usr/lib/go/src/testing/testing.go:888 +0x2c3
testing.(*M).Run(0xc4201baf20, 0xc42005df20)
	/usr/lib/go/src/testing/testing.go:822 +0xfe
main.main()
	github.com/libgit2/git2go/_test/_testmain.go:184 +0xf9

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 56 [runnable]:
syscall.Syscall6(0x101, 0xffffffffffffff9c, 0xc42058a0a0, 0x80000, 0x0, 0x0, 0x0, 0x5, 0x80000, 0x0)
	/usr/lib/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.openat(0xffffffffffffff9c, 0xc4201c2020, 0x15, 0x80000, 0xc400000000, 0xc420232000, 0xc4203b2038, 0x0)
	/usr/lib/go/src/syscall/zsyscall_linux_amd64.go:40 +0xd2
syscall.Open(0xc4201c2020, 0x15, 0x80000, 0x96900000000, 0xc4201c2020, 0x15, 0xc4201c2025)
	/usr/lib/go/src/syscall/syscall_linux.go:51 +0x52
os.OpenFile(0xc4201c2020, 0x15, 0x0, 0x0, 0x0, 0xc42026a030, 0xc4203b2000)
	/usr/lib/go/src/os/file_unix.go:97 +0x82
os.Open(0xc4201c2020, 0x15, 0x969055cc380, 0xc4203b2000, 0x0)
	/usr/lib/go/src/os/file.go:247 +0x48
os.RemoveAll(0xc4201c2020, 0x15, 0x15, 0xc42004af48)
	/usr/lib/go/src/os/path.go:87 +0x205
github.com/libgit2/git2go.cleanupTestRepo(0xc42016c820, 0xc420214480)
	/home/powerman/gocode/src/github.com/libgit2/git2go/git_test.go:16 +0xc0
github.com/libgit2/git2go.TestRemoteConnect(0xc42016c820)
	/home/powerman/gocode/src/github.com/libgit2/git2go/remote_test.go:66 +0x140
testing.tRunner(0xc42016c820, 0x969054f46a8)
	/usr/lib/go/src/testing/testing.go:657 +0x98
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:697 +0x2cc

goroutine 57 [syscall, locked to thread]:
github.com/libgit2/git2go._Cfunc_git_remote_connect(0x6b4278006a70, 0xc400000000, 0xc4200c4000, 0xc4203db530, 0xc42022e3a0, 0x6b4200000000)
	github.com/libgit2/git2go/_test/_obj_test/_cgo_gotypes.go:5376 +0x4f
github.com/libgit2/git2go.(*Remote).Connect.func1(0x6b4278006a70, 0x96900000000, 0xc4200c4000, 0xc4203db530, 0xc42022e3a0, 0x6b4278003610)
	/home/powerman/gocode/src/github.com/libgit2/git2go/remote.go:747 +0x248
github.com/libgit2/git2go.(*Remote).Connect(0xc4202542d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/powerman/gocode/src/github.com/libgit2/git2go/remote.go:747 +0x233
github.com/libgit2/git2go.(*Remote).ConnectFetch(0xc4202542d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/powerman/gocode/src/github.com/libgit2/git2go/remote.go:716 +0x6b
github.com/libgit2/git2go.TestRemoteLs(0xc42016c8f0)
	/home/powerman/gocode/src/github.com/libgit2/git2go/remote_test.go:76 +0x137
testing.tRunner(0xc42016c8f0, 0x969054f46b8)
	/usr/lib/go/src/testing/testing.go:657 +0x98
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:697 +0x2cc

goroutine 58 [syscall, locked to thread]:
github.com/libgit2/git2go._Cfunc_git_remote_connect(0x6b427c000a70, 0xc400000000, 0xc42034e000, 0xc4203fe000, 0xc420210020, 0x6b4200000000)
	github.com/libgit2/git2go/_test/_obj_test/_cgo_gotypes.go:5376 +0x4f
github.com/libgit2/git2go.(*Remote).Connect.func1(0x6b427c000a70, 0x96900000000, 0xc42034e000, 0xc4203fe000, 0xc420210020, 0x6b427c001cd0)
	/home/powerman/gocode/src/github.com/libgit2/git2go/remote.go:747 +0x248
github.com/libgit2/git2go.(*Remote).Connect(0xc4202a2050, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/powerman/gocode/src/github.com/libgit2/git2go/remote.go:747 +0x233
github.com/libgit2/git2go.(*Remote).ConnectFetch(0xc4202a2050, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/powerman/gocode/src/github.com/libgit2/git2go/remote.go:716 +0x6b
github.com/libgit2/git2go.TestRemoteLsFiltering(0xc42016c9c0)
	/home/powerman/gocode/src/github.com/libgit2/git2go/remote_test.go:95 +0x137
testing.tRunner(0xc42016c9c0, 0x969054f46b0)
	/usr/lib/go/src/testing/testing.go:657 +0x98
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:697 +0x2cc

goroutine 59 [chan send]:
testing.tRunner.func1(0xc42016ca90)
	/usr/lib/go/src/testing/testing.go:652 +0x206
testing.tRunner(0xc42016ca90, 0x969054f46c0)
	/usr/lib/go/src/testing/testing.go:659 +0xa2
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:697 +0x2cc

goroutine 60 [chan send]:
testing.tRunner.func1(0xc42016cb60)
	/usr/lib/go/src/testing/testing.go:652 +0x206
testing.tRunner(0xc42016cb60, 0x969054f46c8)
	/usr/lib/go/src/testing/testing.go:659 +0xa2
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:697 +0x2cc

goroutine 61 [chan send]:
testing.tRunner.func1(0xc42016cc30)
	/usr/lib/go/src/testing/testing.go:652 +0x206
testing.tRunner(0xc42016cc30, 0x969054f46e0)
	/usr/lib/go/src/testing/testing.go:659 +0xa2
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:697 +0x2cc

goroutine 62 [chan send]:
testing.tRunner.func1(0xc42016cd00)
	/usr/lib/go/src/testing/testing.go:652 +0x206
testing.tRunner(0xc42016cd00, 0x969054f46f8)
	/usr/lib/go/src/testing/testing.go:659 +0xa2
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:697 +0x2cc

goroutine 63 [chan send]:
testing.tRunner.func1(0xc42016cdd0)
	/usr/lib/go/src/testing/testing.go:652 +0x206
testing.tRunner(0xc42016cdd0, 0x969054f46f0)
	/usr/lib/go/src/testing/testing.go:659 +0xa2
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:697 +0x2cc

goroutine 64 [chan send]:
testing.tRunner.func1(0xc42016cea0)
	/usr/lib/go/src/testing/testing.go:652 +0x206
testing.tRunner(0xc42016cea0, 0x969054f46e8)
	/usr/lib/go/src/testing/testing.go:659 +0xa2
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:697 +0x2cc

goroutine 68 [chan send]:
testing.tRunner.func1(0xc420194c30)
	/usr/lib/go/src/testing/testing.go:652 +0x206
testing.tRunner(0xc420194c30, 0x969054f4718)
	/usr/lib/go/src/testing/testing.go:659 +0xa2
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:697 +0x2cc

goroutine 69 [chan send]:
testing.tRunner.func1(0xc420194d00)
	/usr/lib/go/src/testing/testing.go:652 +0x206
testing.tRunner(0xc420194d00, 0x969054f4720)
	/usr/lib/go/src/testing/testing.go:659 +0xa2
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:697 +0x2cc

goroutine 70 [chan send]:
testing.tRunner.func1(0xc420194dd0)
	/usr/lib/go/src/testing/testing.go:652 +0x206
testing.tRunner(0xc420194dd0, 0x969054f4728)
	/usr/lib/go/src/testing/testing.go:659 +0xa2
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:697 +0x2cc

goroutine 71 [chan send]:
testing.tRunner.func1(0xc420194ea0)
	/usr/lib/go/src/testing/testing.go:652 +0x206
testing.tRunner(0xc420194ea0, 0x969054f4558)
	/usr/lib/go/src/testing/testing.go:659 +0xa2
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:697 +0x2cc

goroutine 72 [chan send]:
testing.tRunner.func1(0xc420194f70)
	/usr/lib/go/src/testing/testing.go:652 +0x206
testing.tRunner(0xc420194f70, 0x969054f4550)
	/usr/lib/go/src/testing/testing.go:659 +0xa2
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:697 +0x2cc

goroutine 73 [chan send]:
testing.tRunner.func1(0xc420195040)
	/usr/lib/go/src/testing/testing.go:652 +0x206
testing.tRunner(0xc420195040, 0x969054f45f0)
	/usr/lib/go/src/testing/testing.go:659 +0xa2
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:697 +0x2cc

goroutine 74 [chan send]:
testing.tRunner.func1(0xc420195110)
	/usr/lib/go/src/testing/testing.go:652 +0x206
testing.tRunner(0xc420195110, 0x969054f45e8)
	/usr/lib/go/src/testing/testing.go:659 +0xa2
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:697 +0x2cc

goroutine 75 [chan send]:
testing.tRunner.func1(0xc4201951e0)
	/usr/lib/go/src/testing/testing.go:652 +0x206
testing.tRunner(0xc4201951e0, 0x969054f4730)
	/usr/lib/go/src/testing/testing.go:659 +0xa2
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:697 +0x2cc

goroutine 76 [chan send]:
testing.tRunner.func1(0xc4201952b0)
	/usr/lib/go/src/testing/testing.go:652 +0x206
testing.tRunner(0xc4201952b0, 0x969054f4740)
	/usr/lib/go/src/testing/testing.go:659 +0xa2
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:697 +0x2cc

goroutine 77 [chan send]:
testing.tRunner.func1(0xc420195380)
	/usr/lib/go/src/testing/testing.go:652 +0x206
testing.tRunner(0xc420195380, 0x969054f4738)
	/usr/lib/go/src/testing/testing.go:659 +0xa2
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:697 +0x2cc

goroutine 78 [chan receive]:
testing.runTests.func1.1(0xc420080a90)
	/usr/lib/go/src/testing/testing.go:887 +0x49
created by testing.runTests.func1
	/usr/lib/go/src/testing/testing.go:887 +0xb1
exit status 2
FAIL	github.com/libgit2/git2go	0.583s
```

**Comment by carlosmn** [comment]
This is most likely the same cause as #356 where on newer Go it would run the finalizer before we were done with the object it's wrapping.

I believe #387 fixes this, which is included in master and the v26 branch.
